package com.springkotlin.controller.entity

import jakarta.persistence.*

@Entity
@Table(name = "Course")
data class Course(
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    val id: Int?, // nullable because initially it will be null and actual value will be generated by DB.
    val name: String,
    val category: String
)

/**
 * Why do we have dto and entity as separate model?
 * It is because we should not bind the database contract to ui contract. It should be loosely coupled that is the recommend
 * approach.
 *
 * */