package com.springkotlin.controller.dto

data class CourseDTO(
    val id: Int?, // nullable because initially it will be null and actual value will be generated by DB.
    val name: String,
    val category: String
)