package com.springkotlin.controller.dto

import jakarta.validation.constraints.NotBlank


// DTO -> Data transfer object
data class CourseDTO(
    val id: Int?, // nullable because initially it will be null and actual value will be generated by DB.
    @get:NotBlank val name: String,
    @get:NotBlank val category: String
)